# Generated by Django 4.2.15 on 2024-08-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_no", models.CharField(max_length=10)),
                ("month", models.CharField(max_length=20)),
                ("present_days", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BasicPay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_no", models.CharField(max_length=10)),
                ("basic_pay", models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name="IncomeTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_no", models.CharField(max_length=10)),
                ("income_tax", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
