# Generated by Django 4.2.15 on 2024-08-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incometax",
            old_name="income_tax",
            new_name="income_tax_percentage",
        ),
        migrations.RemoveField(model_name="basicpay", name="basic_pay",),
        migrations.AddField(
            model_name="basicpay",
            name="basic_pay_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
